"""Common passwords list for password policy validation.

Contains the top 100+ most commonly used passwords that should be rejected.

**Feature: api-base-improvements, core-improvements-v2**
**Refactored: Extracted from password_policy.py for maintainability**
"""

from typing import Final

# Common passwords list (top 100+ most common)
COMMON_PASSWORDS: Final[frozenset[str]] = frozenset([
    "password",
    "123456",
    "12345678",
    "qwerty",
    "abc123",
    "monkey",
    "1234567",
    "letmein",
    "trustno1",
    "dragon",
    "baseball",
    "iloveyou",
    "master",
    "sunshine",
    "ashley",
    "bailey",
    "passw0rd",
    "shadow",
    "123123",
    "654321",
    "superman",
    "qazwsx",
    "michael",
    "football",
    "password1",
    "password123",
    "batman",
    "login",
    "admin",
    "welcome",
    "hello",
    "charlie",
    "donald",
    "password2",
    "qwerty123",
    "whatever",
    "freedom",
    "nothing",
    "secret",
    "princess",
    "starwars",
    "121212",
    "1234567890",
    "000000",
    "111111",
    "222222",
    "333333",
    "444444",
    "555555",
    "666666",
    "777777",
    "888888",
    "999999",
    "123321",
    "password!",
    "qwertyuiop",
    "asdfghjkl",
    "zxcvbnm",
    "1q2w3e4r",
    "1qaz2wsx",
    "abcd1234",
    "pass1234",
    "test1234",
    "user1234",
    "admin123",
    "root",
    "toor",
    "administrator",
    "guest",
    "default",
    "changeme",
    "temp",
    "test",
    "demo",
    "sample",
    "example",
    "public",
    "private",
    "secure",
    "security",
    "access",
    "system",
    "server",
    "database",
    "network",
    "internet",
    "intranet",
    "website",
    "webmaster",
    "support",
    "helpdesk",
    "service",
    "services",
    "backup",
    "restore",
    "recovery",
    "maintenance",
    "update",
    "upgrade",
    "install",
])
