language: "pt-BR"

tone_instructions: "Seja direto e técnico. Foque em problemas de segurança, performance e manutenibilidade."

reviews:
  auto_review:
    enabled: true
    drafts: false
    base_branches:
      - main
      - develop
  
  high_level_summary: true
  poem: false
  review_status: true
  collapse_walkthrough: false
  
  path_filters:
    - "!.venv/**"
    - "!**/__pycache__/**"
    - "!*.lock"
    - "!.hypothesis/**"
    - "!htmlcov/**"
  
  path_instructions:
    - path: "src/**/*.py"
      instructions: |
        Verifique:
        - Complexidade ciclomática < 10
        - Funções com no máximo 50 linhas
        - Arquivos com no máximo 400 linhas
        - Uso de type hints
        - Tratamento adequado de erros
        - Princípios SOLID
        - Sem secrets hardcoded
        - SQL injection prevention
    
    - path: "tests/**/*.py"
      instructions: |
        Verifique:
        - Cobertura de edge cases
        - Nomenclatura descritiva
        - Arrange-Act-Assert pattern
        - Sem dados sensíveis em fixtures
    
    - path: "alembic/**/*.py"
      instructions: |
        Verifique:
        - Migrations reversíveis
        - Sem dados sensíveis

    - path: "terraform/**/*.tf"
      instructions: |
        Verifique:
        - Sem secrets hardcoded
        - Uso de variáveis para valores sensíveis
        - Tags obrigatórias
        - Encryption at rest habilitado

chat:
  auto_reply: true

early_access: true

knowledge_base:
  learnings:
    scope: auto
