AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Python API Base - AWS Lambda Deployment

# =============================================================================
# Globals
# =============================================================================
Globals:
  Function:
    Timeout: 30
    MemorySize: 512
    Runtime: python3.12
    Architectures:
      - x86_64
    Environment:
      Variables:
        ENVIRONMENT: lambda
        LOG_LEVEL: INFO
        PYTHONPATH: /var/task/src

# =============================================================================
# Parameters
# =============================================================================
Parameters:
  Stage:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - staging
      - prod
    Description: Deployment stage

  DatabaseUrl:
    Type: String
    Default: ""
    Description: Database connection URL (use Secrets Manager in production)

  RedisUrl:
    Type: String
    Default: ""
    Description: Redis connection URL

# =============================================================================
# Resources
# =============================================================================
Resources:
  # API Gateway HTTP API
  HttpApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      StageName: !Ref Stage
      CorsConfiguration:
        AllowOrigins:
          - "*"
        AllowHeaders:
          - "*"
        AllowMethods:
          - "*"
      AccessLogSettings:
        DestinationArn: !GetAtt ApiAccessLogs.Arn
        Format: '{"requestId":"$context.requestId","ip":"$context.identity.sourceIp","method":"$context.httpMethod","path":"$context.path","status":"$context.status","latency":"$context.responseLatency"}'

  # Main API Function
  ApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub python-api-base-${Stage}
      Handler: deployments.serverless.aws_lambda.handler.handler
      CodeUri: ../../../
      Description: Python API Base Lambda Handler
      Events:
        ApiEvent:
          Type: HttpApi
          Properties:
            ApiId: !Ref HttpApi
            Path: /{proxy+}
            Method: ANY
        RootEvent:
          Type: HttpApi
          Properties:
            ApiId: !Ref HttpApi
            Path: /
            Method: ANY
      Environment:
        Variables:
          DATABASE__URL: !Ref DatabaseUrl
          OBSERVABILITY__REDIS_URL: !Ref RedisUrl
          SECURITY__SECRET_KEY: "{{resolve:secretsmanager:python-api-base/secret-key}}"
      Policies:
        - AWSLambdaBasicExecutionRole
        - Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action:
                - secretsmanager:GetSecretValue
              Resource: !Sub arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:python-api-base/*
      VpcConfig:
        SecurityGroupIds:
          - !Ref LambdaSecurityGroup
        SubnetIds:
          - !Ref PrivateSubnet1
          - !Ref PrivateSubnet2
    Metadata:
      BuildMethod: python3.12

  # CloudWatch Log Group
  ApiAccessLogs:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/apigateway/${HttpApi}
      RetentionInDays: 30

  # Lambda Security Group
  LambdaSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security group for Lambda function
      VpcId: !Ref VPC
      SecurityGroupEgress:
        - IpProtocol: -1
          CidrIp: 0.0.0.0/0

  # VPC Resources (minimal for Lambda)
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsHostnames: true
      EnableDnsSupport: true
      Tags:
        - Key: Name
          Value: !Sub python-api-base-${Stage}-vpc

  PrivateSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      CidrBlock: 10.0.1.0/24
      AvailabilityZone: !Select [0, !GetAZs ""]
      Tags:
        - Key: Name
          Value: !Sub python-api-base-${Stage}-private-1

  PrivateSubnet2:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      CidrBlock: 10.0.2.0/24
      AvailabilityZone: !Select [1, !GetAZs ""]
      Tags:
        - Key: Name
          Value: !Sub python-api-base-${Stage}-private-2

# =============================================================================
# Outputs
# =============================================================================
Outputs:
  ApiUrl:
    Description: API Gateway endpoint URL
    Value: !Sub https://${HttpApi}.execute-api.${AWS::Region}.amazonaws.com/${Stage}

  FunctionArn:
    Description: Lambda Function ARN
    Value: !GetAtt ApiFunction.Arn

  FunctionName:
    Description: Lambda Function Name
    Value: !Ref ApiFunction
