"""Application configuration.

Contains settings and constants for the application layer.

**Feature: core-config-restructuring-2025**
"""

from core.config.application.constants import (
    ACCESS_TOKEN_EXPIRE_SECONDS,
    CORS_MAX_AGE_SECONDS,
    CORS_PREFLIGHT_MAX_AGE_SECONDS,
    DEFAULT_PAGE_SIZE,
    DEFAULT_RATE_LIMIT_REQUESTS,
    DEFAULT_REQUEST_SIZE_BYTES,
    DEFAULT_TOKEN_TTL_SECONDS,
    DELETE_RATE_LIMIT_REQUESTS,
    HTTP_BAD_REQUEST,
    HTTP_INTERNAL_SERVER_ERROR,
    HTTP_OK,
    HTTP_SERVICE_UNAVAILABLE,
    HTTP_UNPROCESSABLE_ENTITY,
    IMPORT_REQUEST_SIZE_BYTES,
    MAX_DISPLAY_NAME_LENGTH,
    MAX_EMAIL_LENGTH,
    MAX_PAGE_SIZE,
    MAX_PASSWORD_LENGTH,
    MAX_STORAGE_LIST_KEYS,
    MIN_EMAIL_LENGTH,
    MIN_PAGE_NUMBER,
    MIN_PASSWORD_LENGTH,
    READ_RATE_LIMIT_REQUESTS,
    REFRESH_TOKEN_EXPIRE_SECONDS,
    UPLOAD_REQUEST_SIZE_BYTES,
    WRITE_RATE_LIMIT_REQUESTS,
)
from core.config.application.settings import Settings, get_settings

__all__ = [
    # Constants
    "ACCESS_TOKEN_EXPIRE_SECONDS",
    "CORS_MAX_AGE_SECONDS",
    "CORS_PREFLIGHT_MAX_AGE_SECONDS",
    "DEFAULT_PAGE_SIZE",
    "DEFAULT_RATE_LIMIT_REQUESTS",
    "DEFAULT_REQUEST_SIZE_BYTES",
    "DEFAULT_TOKEN_TTL_SECONDS",
    "DELETE_RATE_LIMIT_REQUESTS",
    "HTTP_BAD_REQUEST",
    "HTTP_INTERNAL_SERVER_ERROR",
    "HTTP_OK",
    "HTTP_SERVICE_UNAVAILABLE",
    "HTTP_UNPROCESSABLE_ENTITY",
    "IMPORT_REQUEST_SIZE_BYTES",
    "MAX_DISPLAY_NAME_LENGTH",
    "MAX_EMAIL_LENGTH",
    "MAX_PAGE_SIZE",
    "MAX_PASSWORD_LENGTH",
    "MAX_STORAGE_LIST_KEYS",
    "MIN_EMAIL_LENGTH",
    "MIN_PAGE_NUMBER",
    "MIN_PASSWORD_LENGTH",
    "READ_RATE_LIMIT_REQUESTS",
    "REFRESH_TOKEN_EXPIRE_SECONDS",
    "UPLOAD_REQUEST_SIZE_BYTES",
    "WRITE_RATE_LIMIT_REQUESTS",
    # Settings
    "Settings",
    "get_settings",
]
