"""Shared module - Generic base classes and utilities."""

from my_api.shared.batch import (
    BatchConfig,
    BatchErrorStrategy,
    BatchOperationBuilder,
    BatchOperationStats,
    BatchOperationType,
    BatchProgress,
    BatchRepository,
    BatchResult,
    IBatchRepository,
    chunk_sequence,
)
from my_api.shared.event_sourcing import (
    Aggregate,
    ConcurrencyError,
    EventSourcedRepository,
    EventStream,
    EventStore,
    InMemoryEventStore,
    InMemoryProjection,
    Projection,
    Snapshot,
    SourcedEvent,
)
from my_api.shared.saga import (
    Saga,
    SagaBuilder,
    SagaContext,
    SagaOrchestrator,
    SagaResult,
    SagaStatus,
    SagaStep,
    StepStatus,
)
from my_api.shared.types import (
    # Annotated Types
    ULID,
    UUID,
    Email,
    HttpUrl,
    ISODateStr,
    JWTToken,
    LongStr,
    MediumStr,
    NonEmptyStr,
    NonNegativeFloat,
    NonNegativeInt,
    PageNumber,
    PageSize,
    Password,
    Percentage,
    PhoneNumber,
    PositiveFloat,
    PositiveInt,
    SecurePassword,
    ShortStr,
    Slug,
    TrimmedStr,
    VersionStr,
    # Type Aliases (PEP 695)
    FilterDict,
    SortOrder,
    QueryParams,
    Headers,
    JSONPrimitive,
    JSONValue,
    JSONObject,
    JSONArray,
    EntityId,
)

__all__ = [
    # Batch Operations
    "BatchConfig",
    "BatchErrorStrategy",
    "BatchOperationBuilder",
    "BatchOperationStats",
    "BatchOperationType",
    "BatchProgress",
    "BatchRepository",
    "BatchResult",
    "IBatchRepository",
    "chunk_sequence",
    # Event Sourcing
    "Aggregate",
    "ConcurrencyError",
    "EventSourcedRepository",
    "EventStore",
    "EventStream",
    "InMemoryEventStore",
    "InMemoryProjection",
    "Projection",
    "Snapshot",
    "SourcedEvent",
    # Saga Pattern
    "Saga",
    "SagaBuilder",
    "SagaContext",
    "SagaOrchestrator",
    "SagaResult",
    "SagaStatus",
    "SagaStep",
    "StepStatus",
    # ID Types
    "ULID",
    "UUID",
    # String Types
    "NonEmptyStr",
    "TrimmedStr",
    "ShortStr",
    "MediumStr",
    "LongStr",
    "Slug",
    # Contact Types
    "Email",
    "PhoneNumber",
    # Numeric Types
    "PositiveInt",
    "NonNegativeInt",
    "PositiveFloat",
    "NonNegativeFloat",
    "Percentage",
    # Pagination Types
    "PageNumber",
    "PageSize",
    # Security Types
    "Password",
    "SecurePassword",
    "JWTToken",
    # URL Types
    "HttpUrl",
    # Code/Technical Types
    "VersionStr",
    "ISODateStr",
    # Type Aliases (PEP 695)
    "FilterDict",
    "SortOrder",
    "QueryParams",
    "Headers",
    "JSONPrimitive",
    "JSONValue",
    "JSONObject",
    "JSONArray",
    "EntityId",
]
